"""Local storage helpers and schemas."""

from paperscout.storage.jsonl_store import (
    append_feedback,
    append_jsonl,
    append_recommendation,
    find_duplicate_recommendation,
    has_recommended_paper,
    load_feedback,
    load_jsonl,
    load_profile,
    load_recommendations,
    read_json,
    read_jsonl,
    save_profile,
    write_json,
)
from paperscout.storage.schemas import (
    DEFAULT_EXPLANATION_STYLE,
    NO_EXTRA_CONSTRAINTS,
    FeedbackRecord,
    PaperMetadata,
    ReaderProfile,
    RecommendationRecord,
    ScoreBreakdown,
    canonicalize_url,
    is_same_paper,
    normalize_arxiv_id,
    normalize_doi,
    shared_identifier_keys,
    utc_now_iso,
)

__all__ = [
    "DEFAULT_EXPLANATION_STYLE",
    "NO_EXTRA_CONSTRAINTS",
    "FeedbackRecord",
    "PaperMetadata",
    "ReaderProfile",
    "RecommendationRecord",
    "ScoreBreakdown",
    "append_feedback",
    "append_jsonl",
    "append_recommendation",
    "canonicalize_url",
    "find_duplicate_recommendation",
    "has_recommended_paper",
    "is_same_paper",
    "load_feedback",
    "load_jsonl",
    "load_profile",
    "load_recommendations",
    "normalize_arxiv_id",
    "normalize_doi",
    "read_json",
    "read_jsonl",
    "save_profile",
    "shared_identifier_keys",
    "utc_now_iso",
    "write_json",
]
